server:
  port: 8888
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dev
    username: sa
    password:
    platform: h2
    separator: ;
  sql:
    init:
      mode: always
  jpa:
    database: h2
    show-sql: true
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      #enabled: false
  thymeleaf:
    cache: false
  mvc:
    log-request-details: true
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
